plugin directory detection cleanup

diff --git a/image-selector b/image-selector
--- a/image-selector
+++ b/image-selector
@@ -1,20 +1,22 @@
 # -*- mode: shell-script -*-
 # vim: ft=zsh fdm=marker :
 
-                                                                     # find out where sxiv is located:
-IMAGE_SELECTOR_SXIV=$HOME/.zsh-image-selector/sxiv                   # - default path
-[ -x "$IMAGE_SELECTOR_SXIV" ] || IMAGE_SELECTOR_SXIV="${0:h}/sxiv"   # - directory with this plugin
-[ -x "$IMAGE_SELECTOR_SXIV" ] || IMAGE_SELECTOR_SXIV="${0:A:h}/sxiv" # - directory with this plugin with symlinks resolved
-[ -x "$IMAGE_SELECTOR_SXIV" ] || IMAGE_SELECTOR_SXIV=sxiv            # - give up and use the global sxiv
-if [ ! -x "$IMAGE_SELECTOR_SXIV" ] &&                                # - sxiv not found
-   [ -z "$commands[sxiv]" ]; then
-    echo 'ERROR: sxiv not found in $PATH' 1>&2
-    return 1
+
+IMAGE_SELECTOR_DIR="${0:A:h}"
+
+IMAGE_SELECTOR_SXIV="$IMAGE_SELECTOR_DIR/sxiv"
+if [ ! -x "$IMAGE_SELECTOR_SXIV" ]; then
+    if [ -n "$commands[sxiv]" ]; then
+        IMAGE_SELECTOR_SXIV=sxiv
+    else
+        echo 'ERROR: sxiv not found in $PATH' 1>&2
+        return 1
+    fi
 fi
 
 W3MIMGDISPLAY=/usr/lib/w3m/w3mimgdisplay
 if [ -x "$W3MIMGDISPLAY" ]; then
-    IMAGE_PREVIEW_SCRIPT="${IMAGE_SELECTOR_SXIV:h}/image-preview"
+    IMAGE_PREVIEW_SCRIPT="$IMAGE_SELECTOR_DIR/image-preview"
     image-preview()
     {
         autoload -U split-shell-arguments
